### ISSUE TITLE
Question about json2html hackedup

### ISSUE THREAD

**Issue by seebrown** [dcarrith/jquery.mobile.lazyloader#12]
interested in knowing why you needed to remove the jquery event registration from the json2html?  Was there issues you were running into using even registration?

(Use the jquery.json2html-3.0.hackedup.js if you want to use inline functions)

**Comment by dcarrith** [comment]
@seebrown - to be honest, it was just laziness.  I couldn't get the inline functions to work, so I hacked up your code so it wouldn't touch the inline functions.  I always planned on revisiting it in the future but just didn't get a chance until your question above nudged me along.  The good news is, I got it working and am now convinced that I just wasn't following directions properly.  For example, the relevant section of my template with the inline function looked like this:

"onclick":"remove_queued_track(${playlist_index}, '${escaped_title}', '${symbolic_link_filename}');"

That wasn't working because it isn't correct.  I guess I didn't get down to the part in your documentation (in reference to onwhatever events) that says "Note that these attributes require an inline function as the value."

I'll be honest though, it took me a lot longer than it probably should have tonight when I revisited it to try and get it working with your official 3.0 release.  But, I didn't actually find that quoted part of the attributes documentation until about a half hour ago.  After that, it was easy enough to get working.  ;)  

Here's the fixed piece of the template:

"onclick":"(function(e){ remove_queued_track( e.obj.playlist_index, \"e.obj.title\", \"e.obj.symbolic_link_filename\" ); })"

Very cool.  It's pretty slick how it does what it does.  Well done!

I'm curious to know if you have any benchmarks to compare to other "compiled" and pre-compiled template engines?  I've seen a lot of benchmarks that basically make pre-compiled {dust} templates look like the winner.  But, I don't think I've seen any benchmarks for json2html.  Someday I might get around to it and will be sure to send them your way if you're interested.   

Anyway, I'll push an update to my documentation and remove the "hackedup" version pronto.

Cheers man.

**Comment by dcarrith** [comment]
Hmm...actually...I did still have to change something to get it working.  I'm not sure if how I defined the template above is still wrong or something but, with your official 3.0 release, and my "corrected" template (part of which is in the excerpt above) I get this error:

TypeError: data.action is not a function
data.action(data);

It seems that line 194:

data.action(data);

Needs to be wrapped with an eval.  

eval(data.action)(data);

I'm not sure how I feel about that considering the security risks of an eval.  But, I guess I can live with it until someone explains to me how it could be exploited.   

As a side note, the attributes documentation for onwhatever events shows the example:

{tag:'span',onclick:function(e){alert(e.obj.name);}

But, without the surrounding () around the inline function as I've done in the "corrected" template excerpt above, I was getting an error about the function needing a name because it was being evaluated as a function declaration rather than a function expression.  

If you confirm/acknowledge the missing eval issue, then I could either clone your repo and make the change I described above and send you a pull request to be merged for a 3.0.1 release or something, or... you can just make the change yourself and include the fix in a future release if you have one planned.  For such a small change the pull request route seems a bit of overkill, but I'd be happy to do it.

**Comment by seebrown** [comment]
Hey Dave,

 Ya any of the events onclick, onwhatever etc.. require an inline function not a string (wanted to get away from the horrible eval statement).  Hence why you sample below didn't work 

"onclick":"(function(e){ remove_queued_track( e.obj.playlist_index, \"e.obj.title\", \"e.obj.symbolic_link_filename\" ); })"

but the one you posed later worked

{tag:'span',onclick:function(e){alert(e.obj.name);}

again the idea behind this was to have inline functions that would then be attached as jquery events without having to perform any eval statements (hence why the syntax to access a property from the original object changes from ${propname} to e.obj.propname) 

Actually the events aren't the only transform property that can have an inline function as a value, so can the rest of the properties of a transform.  So you could do something like this as well

{"tag":"div","html":function(obj) { if(obj.sweet) return('sweet') else return('salty');}}

So I'll think I'll keep this eval out of the equation .. let me know if that makes sense, if not I'll send over a working example that you can try out

-Chad

**Comment by seebrown** [comment]
oh and also on the performance side check out the performance benchmarking files in the repo

/test/performance_comp.html

and it should give you an idea on the performance of the json2html vs other tempting engines line jsrender and jquery templates.  Note that you can't get the same performance as a compiled template but when you're rendering 100 objects it's not too much slower. 

-C

**Comment by dcarrith** [comment]
Hi Chad,

Thanks for the follow up.  I figured out why I still needed to add the eval on line 194.  It's because I'm specifying the templates in my "html_footer" and then passing in the id of the script tag into the lazyloader which then retrieves the template from the DOM when it needs it.  But, since I'm using the jQuery html() method to retrieve the json2html template from the DOM, it's being returned as a string.  Then, I'm running $.parseJSON on it to get it into a state that json2html can use (i.e. a JavaScript object).  Without the quotes around the inline function, the parseJSON was throwing an error.  So, doing it that way requires the inline function to be defined as a string which requires the eval on line 194.  

It seems like the only way around that for my lazyloader is to allow the user to define the template object directly at re-initialization of the lazyloader for a particular page.  Then, it does not need to be retrieved from the DOM and so it will not be a string which requires the $.parseJSON (because it's already an object that can be passed directly to the json2html engine).  I was doing it that way initially until I added support for pre-complied Dust and Handlebars templates.  I'll probably revisit that so I can establish a consistent way to define the templates.  There was a reason I changed it, but can't remember at the moment.  

Cheers,
Dave
